apiVersion: apps/v1
kind: Deployment
metadata:
  name: julioferreira-american-predictor-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: julioferreira-american-predictor
  template:
    metadata:
      labels:
        app: julioferreira-american-predictor
    spec:
      containers:
      - name: julioferreira-american-predictor
        image: julioferreira20/julioferreira-american-predictor:1.5
        ports:
        - containerPort: 5018